name: H.E.M. Core Auto-Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 18.168.21.127
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/hem-cloud
            git fetch origin main
            git reset --hard origin/main
            sudo chown -R www-data:www-data /var/www/hem-cloud
            sudo systemctl restart nginx